version: '3.8'

services:
  backend:
    build: ./backend             
    container_name: test-backend
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env          

  frontend:
    build: ./frontend           
    container_name: test-frontend
    ports:
      - "8080:80"              
    depends_on:
      - backend